apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pccz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pccz
    app.kubernetes.io/part-of: tkrw-pr714-0075-0039-app
  name: devfile-sample-pccz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pccz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pccz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0039-tenant/tkrw-pr714-0075-0039-app/devfile-sample-pccz@sha256:9c611770d4fa6e919cf9477313396bd1b2065640fc2dd38574f6edf6c5bdddb6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
